print("\t|........................................................................|")
print("\t|\t\t  RAMEEN ENTERPRISES\t\t\t\t\t|")
print("\t|\t\t\t\t\t\t\t\t\t|")
print("\t|\tLocation: \tNtinda TechBuz Hub\t\t\t\t|")
print("\t|\tServices: \tBasmati Rice, Body butter,African Crafts\t|")
print("\t|\tContact: \t0775171761\t\t\t\t\t|")
print("\t|\tSlogan: \tQUALITY AT IT'S BEST\t\t\t\t|")
print("\t|........................................................................|")
print("\t\t\t\t 223-063012-27740")
print ("ISLAMIC UNIVERSITY IN UGANDA")